epos-eu/EPOS-DCAT-AP

- examples/EPOS-DCAT-AP_example.xml
> small typo

- examples/WP08/EDSF_WMS-DCAT-AP.xml
Misprint corrected in dct:title
> Misprint corrected

- examples/WP08/EDSF_WFS-DCAT-AP.xml
Better description on dct:title
> Detail added

- examples/WP11/DynVolc.xml
Hi again,
I've just found "HOW TO CONTRIBUTE"
sorry for my previous pull request.
Cheers,
Emmanuel
> dynvolc.xml creation

- examples/WP12/EPOS-DCAT-AP_WP12.xml
Initial draft of WP12 web services and organization
> Initial WP12 web services and organization

- examples/WP11/Volcanic Tremor
This is an example. Some fields must be uploaded
> Create Volcanic Tremor example

- examples/WP12/EPOS-DCAT-AP_WP12.xml
Added CNR, CNRS, UoL and GFZ organizations information, plus CNR-IREA and IPGP affiliated organization. Added persons information for the organizations. Still missing information about CSIC organization and persons
> Added CNR, CNRS, UoL and GFZ organization info

- examples/WP12/EPOS-DCAT-AP_WP12.xml
Added CSIC persons and organizations. Information about WP12 persons and organizations is now complete.
> Added CSIC persons and organizations

- examples/WP16/EPOS-DCAT-AP_WP16.xml
The WebService section contains the definition for the CKAN catalogue service. The content of some fields has to be confirmed.
> Description of service added

- examples/WP11/EPOS-DCAT-AP_WP11_IPGP_sesimic_wavforms.xml
> add xml dcat file in examples of WP11

- examples/WP11/EPOS-DCAT-AP_WP11_IPGP_sesimic_wavforms.xml
> A. Lemarchand

- examples/WP08/EPOS-DCAT-AP_WP08_GFZ.xml
As requested by @rpaciello on her mail from Sept. 4th 2017.
> Add the modifications previously introduced by ICS

- examples/WP16/EPOS-DCAT-AP_WP16.xml
- Error in api call catalogue web service was solved
- Identifiers for persons/organisation were corrected
> Correction API plus identifiers

- examples/WP12/EPOS-DCAT-AP_WP12.xml
completed ORCID and ISNI identifiers, corrected output of the services (xml now) and other minor issues
> completed ORCID and ISNI identifiers

- examples/WP08/EDSF_crustalfaults-WMS-DCAT-AP.xml
- examples/WP08/EDSF_subductions-WMS-DCAT-AP.xml
> EDSF layers

- examples/WP08/EDSF_crustalfaults-WMS-DCAT-AP.xml
- examples/WP08/EDSF_subductions-WMS-DCAT-AP.xml
WMS version 1.1.1 only has been left
> Minor changes

- examples/WP08/EPOS-DCAT-AP_WP08_NOA.xml
> NOA - National Observatory of Athens

- examples/WP08/EPOS-DCAT-AP_WP08_ODC.xml
Hi, I've put tags in the correct order. It validates now.
M
> WP08 ODC example attempt 2

- examples/WP08/EPOS-DCAT-AP_WP08_NOA.xml
- examples/WP09/EPOS-DCAT-AP_WP09_CRL_DATASELECT_STATIONS.xml
Updating with more info, fix old too
> Updating CRL + NOA

- examples/WP15/BoreholeDataIndex_WFS-EPOS-DCAT-AP.xml
- examples/WP15/BoreholeDataIndex_WMS-EPOS-DCAT-AP.xml
- examples/WP15/GeologicalMap_EGDI_WMS-EPOS-DCAT-AP.xml
Adjusting mapping files according to feedback from WP 6/7 for the GUI to use the WMS.
Adding mapping for 1:1M EGDI geological map
> Adjusting mapping files for BoreholeIndex, adding  1:1M EGDI geological map WMS

- examples/WP15/BoreholeDataIndex_WFS-EPOS-DCAT-AP.xml
- examples/WP15/BoreholeDataIndex_WMS-EPOS-DCAT-AP.xml
- examples/WP15/GeologicalMap_EGDI_WMS-EPOS-DCAT-AP.xml
- examples/WP15/WP15_CSW-EPOS-DCAT-AP.xml
- Flagging fields not used by the GUI still pending work with Wayne
> Updating according to Keyworth meeting

- examples/WP11/Wrapped Interferograms.xml
> Update Wrapped Interferograms.xml

- examples/WP13/EPOS-DCAT-AP_WP13_DDSS-008.xml
I've made some small changes to the XML, including the addition of a parameter which I hope should now fix the XML so that it is able to correctly construct a working URL for the web service.
> Fix problems with WP13 DDSS 008 XML

- examples/WP08/EPOS-DCAT-AP_WP08_INGV_AHEAD.xml
The AHEAD OGC WMS has received ID "WP08-DDSS-050", accept this pull to re-enable the service.
> Re-enabled the OGC WMS, an ID is now assigned

- examples/WP14/WP14-DDSS-022-1-12_PREESE_HALL.xml
fix to IG PAS contact identifiers in WP14-DDSS-022-1-12_PREESE_HALL.xml
> fix to IG PAS contact identifiers in WP14-DDSS-022-1-12_PREESE_HALL.xml

- examples/WP13/EPOS-DCAT-AP_WP13_DDSS-002.xml
I've updated DDSS 002 in the same way that we update DDSS 008 in Lisbon, so hopefully it's also working now.
> Updates to WP13-DDSS-002

- examples/WP13/EPOS-DCAT-AP_WP13_DDSS-002.xml
- examples/WP13/EPOS-DCAT-AP_WP13_DDSS-008.xml
I've changed media type in DDSS 2 and 8 to show "txt"
> Fix media type in DDSS 2 and 8

- examples/WP08/EPOS-DCAT-AP_WP08_INGV_AHEAD.xml
Added reference to the H2020 SERA project (https://cordis.europa.eu/project/rcn/210185_en.html)
> Added reference to the H2020 SERA project

- examples/WP11/EPOS-DCAT-AP_WP11_IPGP_sesimic_wavforms.xml
Change according to the discussion with Jan Michalek
> DDSS-ID for station webservice

- EMSC-WebServices_EPOS-DCAT-AP-RDF-Turtle.ttl
EMSC's web services metadata mapping in the standard EPOS-DCAT-AP RDF/Turtle format.
> add EPOS-DCAT-AP RDF/Turtle file

- examples/WP08/WP08-INGV_Dataselect_station_ws.ttl
> modified distribution-type

- examples/WP08/WP08-INGV_Dataselect_station_ws.ttl
> updated to new model, valid

- examples/WP08/WP08-INGV_Dataselect_station_ws.ttl
Here the 'new' version of description of dataselect and station webservices FDSN (validated)
> station ws added

- examples/WP08/WP08-INGV_Dataselect_station_ws.ttl
added , also, correct Italian coordinates
> corrected freq.

- examples/WP08/WP08-INGV_Dataselect_station_ws.ttl
- examples/WP08/WP08-ODC.ttl
Added ORFEUS Data Center services. Includes `fdsnws-dataselect`, `fdsnws-station`, `RRSM shakemap service`.
> Add WP08 ODC services

- examples/WP11/OPGC-WP11-DDSS-036_GAZVOLC.ttl
- examples/WP11/OPGC-WP11-DDSS-047_HOTVOLC.ttl
- examples/WP11/OPGC_WP11-DDSS-024_VOLDORAD.ttl
- examples/WP11/OPGC_WP11-DDSS-036_DYNVOLC.ttl
- examples/WP11/OPGC_WP11-DDSS-049_HOTVOLC.ttl
- examples/WP11/OPGC_WP11-DDSS-050_OI2.ttl
**_For DDSS-047 & DDSS-049 webservice description:_**
- I put the item *hydra:entryPoint* as a comment since the target php page is actually not on-line. It will be online before the end of this week (before 2018-09-14).
> OPGC Update - Correction to be compliant with EPOS Example

- examples/rdf_utils/test_webservice/Pipfile
- examples/rdf_utils/test_webservice/README.md
- examples/rdf_utils/test_webservice/webservice.py
This is a Python utility we have created for checking the web service operations on WP13. It is limited in its scope but has helped up pick up some errors in our metadata files and now successfully tests all or our services. It may be of use to other work packages. If the PR accepted we would also welcome contributions - especially tests which we have yet to add! - for any use cases that this does not handle. 
Please see the README.md file for details.
@SimonFlower
> webservice checking code

- examples/WP16/example_WP16.ttl
Dataset and distribution have been added for one DDSS (WP16-DDSS-003). Dataset is retrieved on the basis of an example defualt value for the parameter 'Keywords'.
Webservice is up and running. (Updated on the 11th of September.)
> Updated example turtle-file

- examples/WP08/WP08-NOA.ttl
the turtle file with the needed descriptions
> WP08-NOA - new file

- examples/WP08/INGV-EDSF_EPOS-DCAT-AP.ttl
-validator ok - default params ok-
> added curl brackets

- examples/rdf_utils/test_webservice/README.md
Some minor changes to the formatting of the test webservice README.
> Update README formatting.

- examples/WP11/WP11_IPGP_DDSS001-002.ttl
validated with http://shacl.org/playground/
> turtle file DDSS001 DDSS002 IPGP

- examples/WP12/EPOS-DCAT-AP_WP12.ttl
This is the updated version of the EPOS-DCAT-AP_WP12.ttl file containing major changes in the operations' descriptions w.r.t. parameters.
> Updated EPOS-DCAT-AP_WP12.ttl

- examples/WP08/WP08-EMSC-fdsnevent_ws.ttl
Request to add the RDF/Turtle file for the EMSC FDSN-event webservice (WP08 seismology)
This service is available at http://www.seismicportal.eu/fdsn-wsevent.html.
Regards
Matthieu Landès
matthieu.landes@gmail.com
> WP08 EMSC: add turtle file for the fdsn event web service

- examples/WP11/WP11_IPGP_DDSS031_volcanoreport.ttl
thanks for reviewing the file and telling me the potential error
> New turtle for VolcanoReports IPGP

- examples/WP11/WP11_IPGP_DDSS001-002.ttl
- examples/WP11/WP11_IPGP_DDSS031_volcanoreport.ttl
1) Check the temporal range that your Dataset covers: done
2) Add hydra:property and schema:valuePattern to the parameters used by your web service (used to filter by temporal range) : done
>  temporal search through EPOS GUI: little adjustment

- examples/WP08/WP8-EMSC-WebServices.ttl
fix bugs and update the configuration of srcmod webservice
> Update WP08 EMSC turtle file

- examples/WP08/WP8-EMSC-WebServices.ttl
remove default value "source_catalog" for moment tensor ws.
> Update WP08 EMSC webservices

- examples/WP08/WP08-ODC.ttl
As per the document distributed
- Added bounding box parameters
- Added `hydra:property` values for `startDate` & `endDate` to `WebService`
> Update WP08 ODC

- examples/WP08/WP8-EMSC-WebServices.ttl
Cleanup and addition of spatial information needed for ICS interaction
> Update ttl file for WP08 EMSC services

- examples/WP11/WP11_IPGP_DDSS001-002.ttl
- examples/WP11/WP11_IPGP_DDSS031_volcanoreport.ttl
refine  spatial metadaa in creating 2 polygones : 
-Antilles  (-64 11,-58 11,-58 18,-64 18,-64 11)
- Réunion (54.5 -21.5 , 56.5 -21.5 , 56.5 -20.5 , 54.5 -20.5 , 54.5 -21.5)
Add hydra:property to define lat/long in webservice parameters
> Update according to guidelines sent by Rossana Pacielo

- examples/WP08/WP8-LMU-20180914.ttl
@rpaciello I think this should be everything that's left to do regarding your current email request (for WP08 LMU FDSN web services). Is there a validation tool to check if everything is in order or something is missing?
CC @jwassermann @heinerigel
> update WP08 LMU ttl: spatial and temporal meta

- tools/check_webservice/webservice.py
This pull request tightens up finding the roots of hydra operations now that hydra:property is used more widely.
> Be stricter in finding root nodes for operations

- examples/WP08/WP08-INGV_Dataselect_station_ws_last.ttl
> updated w/ geobox terms

- examples/WP12/EPOS-DCAT-AP_WP12_v1.2.ttl
Version 1.2 implementing the recent changes requested for the update Temporal information and Spatial information for DDSS discovery.
> Version 1.2

- examples/WP11/CSIC-DDSS-057_new
- examples/WP11/CSIC-DDSS-058_new
- examples/WP11/CSIC-DDSS-059_new
- examples/WP11/CSIC-DDSS-060_new
- examples/WP11/CSiC-DDSS-056_new
- examples/WP11/INGV-DDSS-070
- examples/WP11/INGV_WP11_031_updated
> WP11 upgrade files

- examples/WP11/OPGC-WP11-DDSS-036_GAZVOLC_new.ttl
- examples/WP11/OPGC-WP11-DDSS-047_HOTVOLC_new.ttl
- examples/WP11/OPGC_WP11-DDSS-024_VOLDORAD_new.ttl
- examples/WP11/OPGC_WP11-DDSS-026_collection_rocks_new.ttl
- examples/WP11/OPGC_WP11-DDSS-036_DYNVOLC_new.ttl
- examples/WP11/OPGC_WP11-DDSS-049_HOTVOLC_new.ttl
- examples/WP11/OPGC_WP11-DDSS-050_OI2_new.ttl
- examples/WP11/OPGC_WP11-DDSS-051_lava_map_new.ttl
- examples/WP11/OPGC_WP11-DDSS-053_doppler_spectra_new.ttl
* corrected title
* switch payload to simple json (waiting for discussion with ICS to rework payload)
> OPGC Update

- epos-dcat-ap_shapes.ttl
This PR fixes a couple of typos in comments within the SHACL file.
> Fix a couple of typos in SHACL file

- examples/WP08/WP08-ESM-flatfile-2018.ttl
- examples/WP08/WP08-ESM-shakemap.ttl
ESM flatfile and shakemaps tl quality check following TCS guidelines
> ESM flatfile and shakemaps tl quality check

- examples/WP08/WP8-GFZ-20180911.ttl
Also very minor corrections (e.g. double parenthesis in POLYGON definition).
> Missing hydra:property, Dataset and Distribution.

- examples/WP08/WP8-RESIF-20180913.ttl
Following the comments from @rpaciello
> Various corrections

- examples/WP08/WP08-INGV_Dataselect_station_ws_last.ttl
Please, let me know if all changes are ok.
Many thanks for your help.
> updated w/o acronyms; improved descriptions.

- tools/check_webservice/webservice.py
This PR contains various improvements and fixes to the webservice operation checking tool.
> Revised webservice checking tool

- examples/WP13/EPOS-DCAT-AP_WP13_DDSS-004_MTS.ttl
- examples/WP13/EPOS-DCAT-AP_WP13_DDSS-010_MTF.ttl
- examples/WP13/EPOS-DCAT-AP_WP13_DDSS-013_MOD.ttl
Change in name of magnetotelluric project "EPOS" to "EPOSMT".
> Epos dcat ap shapes
